import axios from 'axios';
const url = 'https://crudcrud.com/api/fae279f1c40646129f04df4cc4cf3388';
//^^url generated by crudcrud, replace
const TRIPS_ENDPOINT = `${url}/packing`;//crudcrud full url
class TripsApi{
    get = async () => {
        const resp = await axios.get(TRIPS_ENDPOINT)
        // .then((response) => console.log(response));
        return resp.data;
    }
    post = async (trip) => {        
        axios.post(TRIPS_ENDPOINT, trip)
        // .then( (response) => console.log(response))
        .catch((error) => console.log(error))
    }
    put = async (trip) => {
        const resp = axios.put(`${TRIPS_ENDPOINT}/${trip._id}`, {
            tripName: trip.tripName, 
            dateString: trip.dateString, 
            tripItems: trip.tripItems
        })
        // .then((response) => console.log(response))
        .catch((error) => console.log(error));
    }
    delete = async(trip) => {
        axios.delete(`${TRIPS_ENDPOINT}/${trip._id}`)
        // .then((response) => console.log(response))
        .catch((error) => console.log(error))
    }
}

export const tripApi = new TripsApi();